# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GpoM7TWuIt_yhljXjg67DeT0vxXaT3Yr
"""

from google.colab import files
uploaded = files.upload()

import gradio as gr
import tensorflow as tf
import numpy as np
import cv2
from PIL import Image
import pandas as pd
import matplotlib.pyplot as plt
import datetime

# ================= MODEL =================
model = tf.keras.models.load_model("wafer_model.keras")

class_names = [
    "Center","Donut","Edge-Loc","Edge-Ring",
    "Loc","Near-Full","Random","Scratch"
]

history_log = []

# ================= SAFE CONV LAYER =================
def get_last_conv_layer(model):
    for layer in reversed(model.layers):
        if isinstance(layer, tf.keras.layers.Conv2D):
            return layer.name
    return None

LAST_CONV_LAYER = get_last_conv_layer(model)

# ================= GRADCAM =================
def make_gradcam_heatmap(img_array):

    if LAST_CONV_LAYER is None:
        return np.zeros((224,224))

    grad_model = tf.keras.models.Model(
        [model.inputs],
        [model.get_layer(LAST_CONV_LAYER).output, model.output]
    )

    with tf.GradientTape() as tape:
        conv_outputs, predictions = grad_model(img_array)
        pred_index = tf.argmax(predictions[0])
        class_channel = predictions[:, pred_index]

    grads = tape.gradient(class_channel, conv_outputs)
    pooled_grads = tf.reduce_mean(grads, axis=(0,1,2))

    conv_outputs = conv_outputs[0]
    heatmap = conv_outputs @ pooled_grads[..., tf.newaxis]
    heatmap = tf.squeeze(heatmap)

    heatmap = tf.maximum(heatmap, 0)

    if tf.reduce_max(heatmap) == 0:
        return np.zeros((224,224))

    heatmap /= tf.reduce_max(heatmap)
    return heatmap.numpy()

# ================= CHARTS =================
def plot_confidence(conf):
    fig = plt.figure()
    plt.bar(["Confidence"], [conf])
    plt.ylim(0,1)
    return fig

def plot_distribution():
    if len(history_log)==0:
        return None
    df = pd.DataFrame(history_log)
    fig = plt.figure()
    df["Defect"].value_counts().plot(kind="bar")
    return fig

# ================= REPORT =================
def generate_report():
    if len(history_log)==0:
        return None
    df = pd.DataFrame(history_log)
    file = "wafer_report.csv"
    df.to_csv(file,index=False)
    return file

# ================= MAIN ANALYSIS =================
def analyze_single(image):

    # ⭐ INPUT VALIDATION
    if image is None:
        return (
            "❌ Please Upload Image",
            0,
            "No Data",
            np.zeros((224,224,3),dtype=np.uint8),
            None,
            None,
            pd.DataFrame()
        )

    try:
        image = image.convert("RGB")
        original = image.copy()

        image = image.resize((224,224))
        img_array = np.array(image)/255.0
        img_array = np.expand_dims(img_array,axis=0)

        prediction = model.predict(img_array)

        predicted_class = class_names[np.argmax(prediction)]
        confidence = float(np.max(prediction))

        # Reliability
        if confidence>0.75:
            reliability="🟢 High"
        elif confidence>0.60:
            reliability="🟡 Moderate"
        else:
            reliability="🔴 Low"

        # GradCAM
        heatmap = make_gradcam_heatmap(img_array)

        original = np.array(original.resize((224,224)))

        heatmap = cv2.resize(heatmap,(224,224))
        heatmap = np.uint8(255*heatmap)
        heatmap = cv2.applyColorMap(heatmap, cv2.COLORMAP_JET)

        result_img = cv2.addWeighted(original,0.6,heatmap,0.4,0)

        # Log history
        history_log.append({
            "Time": datetime.datetime.now(),
            "Defect": predicted_class,
            "Confidence": confidence
        })

        df_history = pd.DataFrame(history_log)

        return (
            predicted_class,
            confidence,
            reliability,
            result_img,
            plot_confidence(confidence),
            plot_distribution(),
            df_history
        )

    except Exception as e:
        print("ERROR:",e)
        return (
            "Processing Error",
            0,
            "Failed",
            np.zeros((224,224,3),dtype=np.uint8),
            None,
            None,
            pd.DataFrame()
        )

# ================= UI =================
with gr.Blocks(theme=gr.themes.Soft()) as demo:

    gr.Markdown(" AI Wafer Monitoring System")

    with gr.Row():
        input_img = gr.Image(type="pil")
        btn = gr.Button("Analyze")

    with gr.Row():
        out_class = gr.Textbox(label="Defect")
        out_conf = gr.Number(label="Confidence")
        out_rel = gr.Textbox(label="Reliability")

    out_heat = gr.Image(label="GradCAM")

    with gr.Row():
        conf_chart = gr.Plot(label="Confidence Chart")
        dist_chart = gr.Plot(label="Defect Distribution")

    history_table = gr.Dataframe(label="Prediction History")

    report_btn = gr.Button("Download Report")
    report_file = gr.File()

    btn.click(
        analyze_single,
        inputs=input_img,
        outputs=[
            out_class,
            out_conf,
            out_rel,
            out_heat,
            conf_chart,
            dist_chart,
            history_table
        ]
    )

    report_btn.click(generate_report,outputs=report_file)

demo.launch(share=True)